### ISSUE TITLE
SBOM naming: optional mandatory?

### ISSUE THREAD

**Issue by david-a-wheeler** [ossf/sbom-everywhere#40]
The SBOM naming document says:

> The JSON format files should be considered a mandatory requirement and are always available. The tool support for JSON documents is considered to be better than the other file format options. If other formats are desired, also including the JSON SBOM is optional.

The phrase "should be mandatory... optional" is really confusing. Either it's mandatory, or it isn't. "Should" and "optional" mean it's not mandatory. It sounds like you simply want to give a nudge towards including JSON.

How about this instead:

> We recommend supplying one of the JSON format files, at least as *one* of the provided formats, because tool support for JSON documents is generally better than the other file format options.

**Comment by david-a-wheeler** [comment]
@joshbressers - what do you think?

**Comment by joshbressers** [comment]
@david-a-wheeler I updated the text, that was a typo. I would appreciate a review on #43 from you

**Comment by joshbressers** [comment]
This was merged
