### ISSUE TITLE
Protect the main branch

### ISSUE THREAD

**Issue by joshbressers** [ossf/sbom-everywhere#8]
The main branch in this repository is not protected (I accidentally committed to it earlier today). We should have a branch protection rule to prevent this from happening.

**Comment by joshbressers** [comment]
@david-a-wheeler @jorydotcom can one of you help with this?

thanks in advance

**Comment by david-a-wheeler** [comment]
@joshbressers - done, added branch protection on "main". I included a requirement for a reviewer - let me know if that's too much, or if you want any other changes.

**Comment by joshbressers** [comment]
That sounds perfect, thanks!
